version: "3.5"

services:
  react_blog:
    image: oatwant43/react-blog:latest
    container_name: react_blog
    restart: always
    networks:
      - blog_thanathip_proxy
    environment:
      VIRTUAL_HOST: blog.thanathip.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: blog.thanathip.com
      LETSENCRYPT_EMAIL: thanathipch9@gmail.com

networks:
  blog_thanathip_proxy:
    external:
      name: blog_thanathip_proxy
